/**
 * Copyright (c) 2015 nextlets.org
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * The Software shall be used for Good, not Evil.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package org.nextlets.wikistat;

public enum Lang {

    Afar             ("aa"),
    Abkhazian        ("ab"),
    Avestan          ("ae"),
    Afrikaans        ("af"),
    Akan             ("ak"),
    Amharic          ("am"),
    Aragonese        ("an"),
    Arabic           ("ar"),
    Assamese         ("as"),
    Avaric           ("av"),
    Aymara           ("ay"),
    Azerbaijani      ("az"),
    Bashkir          ("ba"),
    Belarusian       ("be"),
    Bulgarian        ("bg"),
    Bihari           ("bh"),
    Bislama          ("bi"),
    Bambara          ("bm"),
    Bengali          ("bn"),
    Tibetan          ("bo"),
    Breton           ("br"),
    Bosnian          ("bs"),
    Catalan          ("ca"),
    Chechen          ("ce"),
    Chamorro         ("ch"),
    Corsican         ("co"),
    Cree             ("cr"),
    Czech            ("cs"),
    ChurchSlavic     ("cu"),
    Chuvash          ("cv"),
    Welsh            ("cy"),
    Danish           ("da"),
    German           ("de"),
    Divehi           ("dv"),
    Dzongkha         ("dz"),
    Ewe              ("ee"),
    Greek            ("el"),
    English          ("en"),
    Esperanto        ("eo"),
    Spanish          ("es"),
    Estonian         ("et"),
    Basque           ("eu"),
    Persian          ("fa"),
    Fulah            ("ff"),
    Finnish          ("fi"),
    Fijian           ("fj"),
    Faroese          ("fo"),
    French           ("fr"),
    WesternFrisian   ("fy"),
    Irish            ("ga"),
    Gaelic           ("gd"),
    Galician         ("gl"),
    Guarani          ("gn"),
    Gujarati         ("gu"),
    Manx             ("gv"),
    Hausa            ("ha"),
    Hebrew           ("he"),
    Hindi            ("hi"),
    HiriMotu         ("ho"),
    Croatian         ("hr"),
    Haitian          ("ht"),
    Hungarian        ("hu"),
    Armenian         ("hy"),
    Herero           ("hz"),
    Interlingua      ("ia"),
    Indonesian       ("id"),
    Interlingue      ("ie"),
    Igbo             ("ig"),
    SichuanYi        ("ii"),
    Inupiaq          ("ik"),
    Ido              ("io"),
    Icelandic        ("is"),
    Italian          ("it"),
    Inuktitut        ("iu"),
    Japanese         ("ja"),
    Javanese         ("jv"),
    Georgian         ("ka"),
    Kongo            ("kg"),
    Kikuyu           ("ki"),
    Kuanyama         ("kj"),
    Kazakh           ("kk"),
    Kalaallisut      ("kl"),
    CentralKhmer     ("km"),
    Kannada          ("kn"),
    Korean           ("ko"),
    Kanuri           ("kr"),
    Kashmiri         ("ks"),
    Kurdish          ("ku"),
    Komi             ("kv"),
    Cornish          ("kw"),
    Kirghiz          ("ky"),
    Latin            ("la"),
    Luxembourgish    ("lb"),
    Ganda            ("lg"),
    Limburgan        ("li"),
    Lingala          ("ln"),
    Lao              ("lo"),
    Lithuanian       ("lt"),
    LubaKatanga      ("lu"),
    Latvian          ("lv"),
    Malagasy         ("mg"),
    Marshallese      ("mh"),
    Maori            ("mi"),
    Macedonian       ("mk"),
    Malayalam        ("ml"),
    Mongolian        ("mn"),
    Marathi          ("mr"),
    Malay            ("ms"),
    Maltese          ("mt"),
    Burmese          ("my"),
    Nauru            ("na"),
    Norwegian        ("nb"),
    NorthNdebele     ("nd"),
    Nepali           ("ne"),
    Ndonga           ("ng"),
    Dutch            ("nl"),
    NorwegianNynorsk ("nn"),
    NorwegianBokmal  ("no"),
    SouthNdebele     ("nr"),
    Navajo           ("nv"),
    Chichewa         ("ny"),
    Occitan          ("oc"),
    Ojibwa           ("oj"),
    Oromo            ("om"),
    Oriya            ("or"),
    Ossetian         ("os"),
    Panjabi          ("pa"),
    Pali             ("pi"),
    Polish           ("pl"),
    Pushto           ("ps"),
    Portuguese       ("pt"),
    Quechua          ("qu"),
    Romansh          ("rm"),
    Rundi            ("rn"),
    Romanian         ("ro"),
    Russian          ("ru"),
    Kinyarwanda      ("rw"),
    Sanskrit         ("sa"),
    Sardinian        ("sc"),
    Sindhi           ("sd"),
    NorthernSami     ("se"),
    Sango            ("sg"),
    Sinhala          ("si"),
    Slovak           ("sk"),
    Slovenian        ("sl"),
    Samoan           ("sm"),
    Shona            ("sn"),
    Somali           ("so"),
    Albanian         ("sq"),
    Serbian          ("sr"),
    Swati            ("ss"),
    Sotho            ("st"),
    Sundanese        ("su"),
    Swedish          ("sv"),
    Swahili          ("sw"),
    Tamil            ("ta"),
    Telugu           ("te"),
    Tajik            ("tg"),
    Thai             ("th"),
    Tigrinya         ("ti"),
    Turkmen          ("tk"),
    Tagalog          ("tl"),
    Tswana           ("tn"),
    Tonga            ("to"),
    Turkish          ("tr"),
    Tsonga           ("ts"),
    Tatar            ("tt"),
    Twi              ("tw"),
    Tahitian         ("ty"),
    Uighur           ("ug"),
    Ukrainian        ("uk"),
    Urdu             ("ur"),
    Uzbek            ("uz"),
    Venda            ("ve"),
    Vietnamese       ("vi"),
    Volapuk          ("vo"),
    Walloon          ("wa"),
    Wolof            ("wo"),
    Xhosa            ("xh"),
    Yiddish          ("yi"),
    Yoruba           ("yo"),
    Zhuang           ("za"),
    Chinese          ("zh"),
    Zulu             ("zu");
        
    private String code;

    Lang(String code) {
        this.code = code;
    }

    public String getCode() {
        return this.code;
    }

}
